// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type NewTweet struct {
	Content string `json:"content"`
	UserID  string `json:"userId"`
}

type Tweet struct {
	ID            string `json:"id"`
	Content       string `json:"content"`
	LikesCount    *int   `json:"likes_count"`
	RetweetsCount *int   `json:"retweets_count"`
	User          *User  `json:"user"`
}

type User struct {
	ID       string `json:"id"`
	Username string `json:"username"`
}
